preset: psr12

enabled:
    - no_trailing_comma_in_singleline_array
    - no_singleline_whitespace_before_semicolons
    - no_unused_imports
    - ordered_imports
    - single_quote
    - no_extra_consecutive_blank_lines
    - phpdoc_no_package
    - phpdoc_scalar
    - no_blank_lines_after_phpdoc
    - short_array_syntax
    - whitespace_after_comma_in_array
    - hash_to_slash_comment
    - native_function_casing
    - no_empty_statement
    - no_short_bool_cast
    - no_unneeded_control_parentheses

finder:
  name:
    - "*.php"
  not-path:
    - ".Build"
    - "Build/php-cs-fixer"
    - "Documentation"
