settings:
  news.rss.channel.title:
    label: 'Rss Channel title'
    type: string
    default: 'Dummy Title'
    description: ''
  news.rss.channel.description:
    label: 'Rss Channel description'
    type: string
    description: ''
  news.rss.channel.link:
    label: 'Rss Channel link'
    type: string
    default: 'http://example.com'
    description: ''
  news.rss.channel.language:
    label: 'Rss Channel language'
    type: string
    default: 'en-gb'
    description: ''
  news.rss.channel.copyright:
    label: 'Rss Channel copyright'
    type: string
    default: 'TYPO3 News'
    description: ''
  news.rss.channel.category:
    label: 'Rss Channel category'
    type: string
    description: ''
  news.rss.channel.generator:
    label: 'Rss Channel generator'
    type: string
    default: 'TYPO3 EXT:news'
    description: ''
  news.rss.channel.typeNum:
    label: 'Rss Channel typeNum'
    type: int
    default: 9818
    description: ''
  news.rss.channel.ttl:
    label: 'Rss Channel ttl'
    type: int
    description: 'Number of minutes the feed can stay cached'
  news.opengraph.site_name:
    label: 'Open Graph site name'
    type: string
    description: ''
  news.opengraph.twitter.card:
    label: 'Open Graph twitter card'
    type: string
    enum:
      'summary': 'Summary Card'
      'summary_large_image': 'Summary Card with Large Image'
      'app': 'App Card'
      'player': 'Player Card'
      'photo': 'Photo Card'
      'gallery': 'Gallery Card'
      'poll': 'Poll Card'
    default: 'summary'
    description: ''
  news.opengraph.twitter.site:
    label: 'Open Graph twitter site'
    type: string
    description: ''
  news.opengraph.twitter.creator:
    label: 'Open Graph twitter creator'
    type: string
    description: ''
  news.view.templateRootPath:
    label: 'Path to template root (FE)'
    type: string
    default: 'EXT:news/Resources/Private/Templates/Templates/'
    description: ''
  news.view.partialRootPath:
    label: 'Path to template partials (FE)'
    type: string
    default: 'EXT:news/Resources/Private/Templates/Partials/'
    description: ''
  news.view.layoutRootPath:
    label: 'Path to template layouts (FE)'
    type: string
    default: 'EXT:news/Resources/Private/Templates/Layouts/'
    description: ''
  news.settings.cssFile:
    label: 'Path to CSS file'
    type: string
    default: 'EXT:news/Resources/Public/Css/news-basic.css'
    description: ''
