news.view.templateRootPath: 'EXT:news/Resources/Private/Templates/Styles/Twb5/Templates/'
news.view.partialRootPath: 'EXT:news/Resources/Private/Templates/Styles/Twb5/Partials/'
news.view.layoutRootPath: 'EXT:news/Resources/Private/Templates/Styles/Twb5/Layouts/'