settings:
  news.view.twb5.templateRootPath:
    label: 'Path to template root (FE)'
    type: string
    default: 'EXT:news/Resources/Private/Templates/Styles/Twb5/Templates/'
    description: ''
  news.view.twb5.partialRootPath:
    label: 'Path to template partials (FE)'
    type: string
    default: 'EXT:news/Resources/Private/Templates/Styles/Twb5/Partials/'
    description: ''
  news.view.twb5.layoutRootPath:
    label: 'Path to template layouts (FE)'
    type: string
    default: 'EXT:news/Resources/Private/Templates/Styles/Twb5/Layouts/'
    description: ''
