news.view.templateRootPath: 'EXT:news/Resources/Private/Templates/Styles/Twb4/Templates/'
news.view.partialRootPath: 'EXT:news/Resources/Private/Templates/Styles/Twb4/Partials/'
news.view.layoutRootPath: 'EXT:news/Resources/Private/Templates/Styles/Twb4/Layouts/'