name: core 12

on: [ push, pull_request ]

jobs:
  tests:
    name: v12
    runs-on: ubuntu-20.04
    strategy:
      # This prevents cancellation of matrix job runs, if one/two already failed and let the
      # rest matrix jobs be be executed anyway.
      fail-fast: false
      matrix:
        php: [ '8.1' ]
        composerInstall: [ 'composerInstallLowest', 'composerInstallHighest' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install testing system
        run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }}  -s ${{ matrix.composerInstall }}

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }} -s lint

# @todo disabled - php-cs-fixer direct inclusion or migration to typo3/coding-standards ?
#        - name: Validate code against CGL
#          run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }} -s cgl -n

      - name: Functional Tests with mariadb and mysqli
        run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }} -d mariadb -a mysqli -s functional

      - name: Functional Tests with mariadb and pdo_mysql
        run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }} -d mariadb -a pdo_mysql -s functional

      - name: Functional Tests with mysql and mysqli
        run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }} -d mysql -a mysqli -s functional

      - name: Functional Tests with mysql and pdo_mysql
        run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }} -d mysql -a pdo_mysql -s functional

# @todo disabled, due cross dbmns issues in code. Should be fixed first
#        - name: Functional Tests with postgres
#          run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }} -d postgres -s functional

# @todo disabled, due cross dbmns issues in code. Should be fixed first
#        - name: Functional Tests with sqlite
#          run: Build/Scripts/runTests.sh -t 12 -p ${{ matrix.php }} -d sqlite -s functional